SERVICE_CATALOG = {
    "api-gateway": {
        "service_code": "api-gateway",
        "service_name": "API 网关",
        "domain": "平台基础能力层",
        "backend_port": 8000,
        "frontend_path": None,
        "tags": ["gateway", "platform"],
        "summary": "统一 API 入口、服务路由与跨域治理。",
    },
    "admin-console": {
        "service_code": "admin-console",
        "service_name": "统一管理后台",
        "domain": "平台基础能力层",
        "backend_port": 8010,
        "frontend_path": "frontends/admin-portal",
        "tags": ["admin", "platform"],
        "summary": "统一管理各业务系统菜单、租户、角色、运行状态与配置。",
    },
    "identity-access": {
        "service_code": "identity-access",
        "service_name": "认证与访问控制",
        "domain": "基础平台域",
        "backend_port": 8001,
        "frontend_path": "frontends/apps/identity-access",
        "tags": ["identity", "platform"],
        "summary": "处理登录、令牌、会话和客户端接入认证。",
    },
    "org-user": {
        "service_code": "org-user",
        "service_name": "组织与用户中心",
        "domain": "基础平台域",
        "backend_port": 8002,
        "frontend_path": "frontends/apps/org-user",
        "tags": ["org", "user"],
        "summary": "维护组织架构、人员主体和跨系统用户主数据。",
    },
    "academic-master": {
        "service_code": "academic-master",
        "service_name": "教务主数据中心",
        "domain": "基础平台域",
        "backend_port": 8003,
        "frontend_path": "frontends/apps/academic-master",
        "tags": ["academic", "master-data"],
        "summary": "沉淀学年学期、班级、课程和教学班等权威主数据。",
    },
    "academic-core": {
        "service_code": "academic-core",
        "service_name": "教务核心服务",
        "domain": "教务管理域",
        "backend_port": 8004,
        "frontend_path": "frontends/apps/academic-core",
        "tags": ["academic", "schedule"],
        "summary": "承载教学计划、选课、排课与调课等核心业务。",
    },
    "student-growth": {
        "service_code": "student-growth",
        "service_name": "学生成长服务",
        "domain": "学人发展域",
        "backend_port": 8005,
        "frontend_path": "frontends/apps/student-growth",
        "tags": ["student", "growth"],
        "summary": "管理学生信息、考勤、请假和成长档案。",
    },
    "oa-collaboration": {
        "service_code": "oa-collaboration",
        "service_name": "OA 协同服务",
        "domain": "协同办公域",
        "backend_port": 8006,
        "frontend_path": "frontends/apps/oa-collaboration",
        "tags": ["oa", "workflow"],
        "summary": "支撑通知、审批、日程和资源预约协同。",
    },
    "question-bank": {
        "service_code": "question-bank",
        "service_name": "题库服务",
        "domain": "教学评测域",
        "backend_port": 8007,
        "frontend_path": "frontends/apps/question-bank",
        "tags": ["exam", "question"],
        "summary": "维护题目、试卷、知识点与组卷配置。",
    },
    "exam-orchestration": {
        "service_code": "exam-orchestration",
        "service_name": "考试编排服务",
        "domain": "教学评测域",
        "backend_port": 8008,
        "frontend_path": "frontends/apps/exam-orchestration",
        "tags": ["exam", "orchestration"],
        "summary": "编排考试任务、考场计划与答卷提交流程。",
    },
    "marking-engine": {
        "service_code": "marking-engine",
        "service_name": "阅卷引擎",
        "domain": "教学评测域",
        "backend_port": 8009,
        "frontend_path": "frontends/apps/marking-engine",
        "tags": ["marking", "engine"],
        "summary": "订阅评测事件并执行自动评分与人工复核。",
    },
}
